### ISSUE TITLE
Отсутствует вычисление суммы баланса счёта "From" и баланса счёта "To" в методе transfer в классе Bank

### ISSUE THREAD

**Issue by Marpolle** [Marpolle/Team-project1#22]
# Описание
Отсутствует вычисление суммы баланса счёта"From" и и баланса счёта "To" . Баланс счёта "From" должен уменьшаться на сумму перевода, баланс счёта "To" должен увеличиваться на сумму перевода.
# Локация дефекта
https://github.com/Marpolle/Team-project1/blob/9dffbf31b63dea3decd3f00904d7018937920393/src/main/java/ru/netology/javaqadiplom/Bank.java#L16
# Шаги воспроизведения
1. Открыть [код программы](https://github.com/Marpolle/Team-project1/blob/saving/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java) в IDEA.
2. Cоздать объект класса Account from с начальным балансом: 1000, Account to с начальным балансом: 2000.
3. Выполнить перевод со счета "From" на счет "To" на сумму 500 рублей
*Ожидаемый результат:* Баланс счёта "From" 500 рублей
*Фактический результат:* Баланс счёта "From" 1000 рублей
# Скриншот
![image](https://github.com/Marpolle/Team-project1/assets/165153697/f2a34b50-7b00-49b3-9cf3-3657069a1c51)
https://github.com/Marpolle/Team-project1/blob/dc58abe0db7faf0274d18d72526b54cb4f912612/src/test/java/BankTest.java#L10
# Окружение
* **Операционная система:** Windows 11 23H2
* **IDE:** IntelliJ IDEA Community Edition 2024.1.1
* **Java:** OpenJDK 11

**Comment by VikaEra** [comment]
Метод и тест исправлены. Тест проходит.


# Скриншоты

![BankNew](https://github.com/Marpolle/Team-project1/assets/167620734/711a089f-8d85-4ed2-889e-1f2c3fccd5cd)
![BankTestNew](https://github.com/Marpolle/Team-project1/assets/167620734/34856699-c07a-431f-8833-bfc323640997)
