### ISSUE TITLE
Нельзя перевести всю сумму со счёта "From" на счёт "To" в классе Bank

### ISSUE THREAD

**Issue by Marpolle** [Marpolle/Team-project1#23]
# Описание
Не выполняется перевод всей суммы со счёта "From" на счёт "To" в методе transfer
# Локация дефекта
https://github.com/Marpolle/Team-project1/blob/9dffbf31b63dea3decd3f00904d7018937920393/src/main/java/ru/netology/javaqadiplom/Bank.java#L16
# Шаги воспроизведения

1. Открыть [код программы](https://github.com/Marpolle/Team-project1/blob/saving/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java) в IDEA.
2. Вводим баланс счета, с которого переводим: 3000, балансом счета на который переводим: : 1000
3. Сделать перевод всей суммы на счёте "From" равной 3000
*Ожидаемый результат:* Баланс на счёте "From" станет равен 0
*Фактический результат:* Баланс на счёте "From"равен изначальному, то есть 3000
# Скриншот
![image](https://github.com/Marpolle/Team-project1/assets/165153697/9742baa0-df3d-41ca-9077-79e98bea8e08)
https://github.com/Marpolle/Team-project1/blob/dc58abe0db7faf0274d18d72526b54cb4f912612/src/test/java/BankTest.java#L28
* **Операционная система:** Windows 11 23H2
* **IDE:** IntelliJ IDEA Community Edition 2024.1.1
* **Java:** OpenJDK 11

**Comment by VikaEra** [comment]
Метод и тест исправлены. Тест проходит.

![BankNew](https://github.com/Marpolle/Team-project1/assets/167620734/61044b83-ebf2-4f6e-8371-54722094ec0a)
![BankTestNew2](https://github.com/Marpolle/Team-project1/assets/167620734/9b952572-3ac4-43cc-8e9e-4785a32d5fda)
